services:
  app:
    image: 'jc21/nginx-proxy-manager:2.12.3'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ""
      DB_MYSQL_PASSWORD: ""
      DB_MYSQL_NAME: "npm"
    volumes:
      - /srv/config/nginxproxymanager:/data
      - /srv/config/nginxproxymanager/letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  db:
    image: 'jc21/mariadb-aria:10.4.15'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: ''
      MYSQL_PASSWORD: ''
    volumes:
      - npm_db:/var/lib/mysql

volumes:
  npm_db:
